# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc

from . import worker_pb2 as worker__pb2


class MasterServiceStub(object):
    """Master service - called by workers"""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.RegisterWorker = channel.unary_unary(
            "/morphml.distributed.MasterService/RegisterWorker",
            request_serializer=worker__pb2.RegisterRequest.SerializeToString,
            response_deserializer=worker__pb2.RegisterResponse.FromString,
        )
        self.Heartbeat = channel.unary_unary(
            "/morphml.distributed.MasterService/Heartbeat",
            request_serializer=worker__pb2.HeartbeatRequest.SerializeToString,
            response_deserializer=worker__pb2.HeartbeatResponse.FromString,
        )
        self.SubmitResult = channel.unary_unary(
            "/morphml.distributed.MasterService/SubmitResult",
            request_serializer=worker__pb2.ResultRequest.SerializeToString,
            response_deserializer=worker__pb2.ResultResponse.FromString,
        )
        self.RequestTask = channel.unary_unary(
            "/morphml.distributed.MasterService/RequestTask",
            request_serializer=worker__pb2.TaskRequest.SerializeToString,
            response_deserializer=worker__pb2.TaskResponse.FromString,
        )


class MasterServiceServicer(object):
    """Master service - called by workers"""

    def RegisterWorker(self, request, context):
        """Register a new worker with the master"""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details("Method not implemented!")
        raise NotImplementedError("Method not implemented!")

    def Heartbeat(self, request, context):
        """Send periodic heartbeat"""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details("Method not implemented!")
        raise NotImplementedError("Method not implemented!")

    def SubmitResult(self, request, context):
        """Submit evaluation result"""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details("Method not implemented!")
        raise NotImplementedError("Method not implemented!")

    def RequestTask(self, request, context):
        """Request a task (pull model)"""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details("Method not implemented!")
        raise NotImplementedError("Method not implemented!")


def add_MasterServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
        "RegisterWorker": grpc.unary_unary_rpc_method_handler(
            servicer.RegisterWorker,
            request_deserializer=worker__pb2.RegisterRequest.FromString,
            response_serializer=worker__pb2.RegisterResponse.SerializeToString,
        ),
        "Heartbeat": grpc.unary_unary_rpc_method_handler(
            servicer.Heartbeat,
            request_deserializer=worker__pb2.HeartbeatRequest.FromString,
            response_serializer=worker__pb2.HeartbeatResponse.SerializeToString,
        ),
        "SubmitResult": grpc.unary_unary_rpc_method_handler(
            servicer.SubmitResult,
            request_deserializer=worker__pb2.ResultRequest.FromString,
            response_serializer=worker__pb2.ResultResponse.SerializeToString,
        ),
        "RequestTask": grpc.unary_unary_rpc_method_handler(
            servicer.RequestTask,
            request_deserializer=worker__pb2.TaskRequest.FromString,
            response_serializer=worker__pb2.TaskResponse.SerializeToString,
        ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
        "morphml.distributed.MasterService", rpc_method_handlers
    )
    server.add_generic_rpc_handlers((generic_handler,))


# This class is part of an EXPERIMENTAL API.
class MasterService(object):
    """Master service - called by workers"""

    @staticmethod
    def RegisterWorker(
        request,
        target,
        options=(),
        channel_credentials=None,
        call_credentials=None,
        insecure=False,
        compression=None,
        wait_for_ready=None,
        timeout=None,
        metadata=None,
    ):
        return grpc.experimental.unary_unary(
            request,
            target,
            "/morphml.distributed.MasterService/RegisterWorker",
            worker__pb2.RegisterRequest.SerializeToString,
            worker__pb2.RegisterResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
        )

    @staticmethod
    def Heartbeat(
        request,
        target,
        options=(),
        channel_credentials=None,
        call_credentials=None,
        insecure=False,
        compression=None,
        wait_for_ready=None,
        timeout=None,
        metadata=None,
    ):
        return grpc.experimental.unary_unary(
            request,
            target,
            "/morphml.distributed.MasterService/Heartbeat",
            worker__pb2.HeartbeatRequest.SerializeToString,
            worker__pb2.HeartbeatResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
        )

    @staticmethod
    def SubmitResult(
        request,
        target,
        options=(),
        channel_credentials=None,
        call_credentials=None,
        insecure=False,
        compression=None,
        wait_for_ready=None,
        timeout=None,
        metadata=None,
    ):
        return grpc.experimental.unary_unary(
            request,
            target,
            "/morphml.distributed.MasterService/SubmitResult",
            worker__pb2.ResultRequest.SerializeToString,
            worker__pb2.ResultResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
        )

    @staticmethod
    def RequestTask(
        request,
        target,
        options=(),
        channel_credentials=None,
        call_credentials=None,
        insecure=False,
        compression=None,
        wait_for_ready=None,
        timeout=None,
        metadata=None,
    ):
        return grpc.experimental.unary_unary(
            request,
            target,
            "/morphml.distributed.MasterService/RequestTask",
            worker__pb2.TaskRequest.SerializeToString,
            worker__pb2.TaskResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
        )


class WorkerServiceStub(object):
    """Worker service - called by master"""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.Evaluate = channel.unary_unary(
            "/morphml.distributed.WorkerService/Evaluate",
            request_serializer=worker__pb2.EvaluateRequest.SerializeToString,
            response_deserializer=worker__pb2.EvaluateResponse.FromString,
        )
        self.GetStatus = channel.unary_unary(
            "/morphml.distributed.WorkerService/GetStatus",
            request_serializer=worker__pb2.StatusRequest.SerializeToString,
            response_deserializer=worker__pb2.StatusResponse.FromString,
        )
        self.Shutdown = channel.unary_unary(
            "/morphml.distributed.WorkerService/Shutdown",
            request_serializer=worker__pb2.ShutdownRequest.SerializeToString,
            response_deserializer=worker__pb2.ShutdownResponse.FromString,
        )
        self.CancelTask = channel.unary_unary(
            "/morphml.distributed.WorkerService/CancelTask",
            request_serializer=worker__pb2.CancelRequest.SerializeToString,
            response_deserializer=worker__pb2.CancelResponse.FromString,
        )


class WorkerServiceServicer(object):
    """Worker service - called by master"""

    def Evaluate(self, request, context):
        """Evaluate an architecture (push model)"""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details("Method not implemented!")
        raise NotImplementedError("Method not implemented!")

    def GetStatus(self, request, context):
        """Get worker status"""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details("Method not implemented!")
        raise NotImplementedError("Method not implemented!")

    def Shutdown(self, request, context):
        """Shutdown worker gracefully"""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details("Method not implemented!")
        raise NotImplementedError("Method not implemented!")

    def CancelTask(self, request, context):
        """Cancel running task"""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details("Method not implemented!")
        raise NotImplementedError("Method not implemented!")


def add_WorkerServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
        "Evaluate": grpc.unary_unary_rpc_method_handler(
            servicer.Evaluate,
            request_deserializer=worker__pb2.EvaluateRequest.FromString,
            response_serializer=worker__pb2.EvaluateResponse.SerializeToString,
        ),
        "GetStatus": grpc.unary_unary_rpc_method_handler(
            servicer.GetStatus,
            request_deserializer=worker__pb2.StatusRequest.FromString,
            response_serializer=worker__pb2.StatusResponse.SerializeToString,
        ),
        "Shutdown": grpc.unary_unary_rpc_method_handler(
            servicer.Shutdown,
            request_deserializer=worker__pb2.ShutdownRequest.FromString,
            response_serializer=worker__pb2.ShutdownResponse.SerializeToString,
        ),
        "CancelTask": grpc.unary_unary_rpc_method_handler(
            servicer.CancelTask,
            request_deserializer=worker__pb2.CancelRequest.FromString,
            response_serializer=worker__pb2.CancelResponse.SerializeToString,
        ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
        "morphml.distributed.WorkerService", rpc_method_handlers
    )
    server.add_generic_rpc_handlers((generic_handler,))


# This class is part of an EXPERIMENTAL API.
class WorkerService(object):
    """Worker service - called by master"""

    @staticmethod
    def Evaluate(
        request,
        target,
        options=(),
        channel_credentials=None,
        call_credentials=None,
        insecure=False,
        compression=None,
        wait_for_ready=None,
        timeout=None,
        metadata=None,
    ):
        return grpc.experimental.unary_unary(
            request,
            target,
            "/morphml.distributed.WorkerService/Evaluate",
            worker__pb2.EvaluateRequest.SerializeToString,
            worker__pb2.EvaluateResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
        )

    @staticmethod
    def GetStatus(
        request,
        target,
        options=(),
        channel_credentials=None,
        call_credentials=None,
        insecure=False,
        compression=None,
        wait_for_ready=None,
        timeout=None,
        metadata=None,
    ):
        return grpc.experimental.unary_unary(
            request,
            target,
            "/morphml.distributed.WorkerService/GetStatus",
            worker__pb2.StatusRequest.SerializeToString,
            worker__pb2.StatusResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
        )

    @staticmethod
    def Shutdown(
        request,
        target,
        options=(),
        channel_credentials=None,
        call_credentials=None,
        insecure=False,
        compression=None,
        wait_for_ready=None,
        timeout=None,
        metadata=None,
    ):
        return grpc.experimental.unary_unary(
            request,
            target,
            "/morphml.distributed.WorkerService/Shutdown",
            worker__pb2.ShutdownRequest.SerializeToString,
            worker__pb2.ShutdownResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
        )

    @staticmethod
    def CancelTask(
        request,
        target,
        options=(),
        channel_credentials=None,
        call_credentials=None,
        insecure=False,
        compression=None,
        wait_for_ready=None,
        timeout=None,
        metadata=None,
    ):
        return grpc.experimental.unary_unary(
            request,
            target,
            "/morphml.distributed.WorkerService/CancelTask",
            worker__pb2.CancelRequest.SerializeToString,
            worker__pb2.CancelResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
        )
