"""Quick-start CLI helper for MorphML.

Provides interactive setup and template generation for common NAS tasks.

Run:
    morphml quickstart
"""

import click
from pathlib import Path
from typing import Optional

from morphml.logging_config import get_logger

logger = get_logger(__name__)


TEMPLATES = {
    "cnn_classification": """\"\"\"CNN Image Classification NAS Example.

Generated by: morphml quickstart
\"\"\"

from morphml.core.dsl import Layer, SearchSpace
from morphml.constraints import ConstraintHandler, MaxParametersConstraint
from morphml.evaluation import HeuristicEvaluator
from morphml.optimizers import GeneticAlgorithm
from morphml.utils import ArchitectureExporter

# Define search space
space = SearchSpace("{name}")
space.add_layers(
    Layer.input(shape=(3, 32, 32)),
    
    # First conv block
    Layer.conv2d(filters=[32, 64], kernel_size=[3, 5]),
    Layer.batchnorm(),
    Layer.relu(),
    Layer.maxpool(pool_size=2),
    
    # Second conv block
    Layer.conv2d(filters=[64, 128], kernel_size=3),
    Layer.batchnorm(),
    Layer.relu(),
    Layer.maxpool(pool_size=2),
    
    # Classification head
    Layer.flatten(),
    Layer.dense(units=[128, 256, 512]),
    Layer.relu(),
    Layer.dropout(rate=[0.3, 0.5]),
    Layer.dense(units={num_classes}),
    Layer.softmax(),
)

# Set up constraints
handler = ConstraintHandler()
handler.add_constraint(MaxParametersConstraint(max_params={max_params}))

# Create evaluator
evaluator = HeuristicEvaluator()

# Configure optimizer
optimizer = GeneticAlgorithm(
    search_space=space,
    config={{
        "population_size": {population_size},
        "num_generations": {num_generations},
        "mutation_rate": 0.2,
        "crossover_rate": 0.8,
    }}
)

# Run optimization
print(f"Starting NAS: {{optimizer.config['num_generations']}} generations...")
best = optimizer.optimize(evaluator)

# Check constraints
if not handler.check(best.graph):
    print("\\nWarning: Best architecture violates constraints:")
    print(handler.format_violations(best.graph))
else:
    print("\\n✓ Best architecture satisfies all constraints")

# Show results
print(f"\\nBest Architecture:")
print(f"  Fitness: {{best.fitness:.4f}}")
print(f"  Parameters: {{best.graph.estimate_parameters():,}}")
print(f"  Depth: {{best.graph.depth()}}")

# Export architecture
exporter = ArchitectureExporter()
pytorch_code = exporter.to_pytorch(best.graph, "{name}_model")

output_file = "{name}_model.py"
with open(output_file, 'w') as f:
    f.write(pytorch_code)

print(f"\\n✓ Exported to {{output_file}}")
""",
    "simple_nas": """\"\"\"Simple NAS Example.

Generated by: morphml quickstart
\"\"\"

from morphml.core.dsl import Layer, SearchSpace
from morphml.evaluation import HeuristicEvaluator
from morphml.optimizers import GeneticAlgorithm

# Define search space
space = SearchSpace("{name}")
space.add_layers(
    Layer.input(shape=(3, 32, 32)),
    Layer.conv2d(filters=[32, 64, 128], kernel_size=3),
    Layer.relu(),
    Layer.maxpool(pool_size=2),
    Layer.flatten(),
    Layer.dense(units=[128, 256]),
    Layer.dense(units={num_classes}),
)

# Run quick search
evaluator = HeuristicEvaluator()
optimizer = GeneticAlgorithm(space, config={{
    "population_size": 10,
    "num_generations": 20,
}})

best = optimizer.optimize(evaluator)
print(f"Best fitness: {{best.fitness:.4f}}")
""",
    "advanced_nas": """\"\"\"Advanced NAS with Adaptive Operators.

Generated by: morphml quickstart
\"\"\"

from morphml.core.dsl import Layer, SearchSpace
from morphml.constraints import ConstraintHandler, MaxParametersConstraint, DepthConstraint
from morphml.evaluation import HeuristicEvaluator
from morphml.optimizers import GeneticAlgorithm
from morphml.optimizers.adaptive_operators import AdaptiveOperatorScheduler
from morphml.visualization.crossover_viz import quick_crossover_viz
from morphml.utils import ArchitectureExporter

# Define search space
space = SearchSpace("{name}")
space.add_layers(
    Layer.input(shape=(3, 32, 32)),
    Layer.conv2d(filters=[32, 64, 128], kernel_size=[3, 5, 7]),
    Layer.batchnorm(),
    Layer.relu(),
    Layer.maxpool(pool_size=2),
    Layer.conv2d(filters=[64, 128, 256], kernel_size=[3, 5]),
    Layer.batchnorm(),
    Layer.relu(),
    Layer.maxpool(pool_size=2),
    Layer.flatten(),
    Layer.dense(units=[128, 256, 512, 1024]),
    Layer.relu(),
    Layer.dropout(rate=[0.3, 0.5, 0.7]),
    Layer.dense(units={num_classes}),
)

# Set up constraints
handler = ConstraintHandler()
handler.add_constraint(MaxParametersConstraint(max_params={max_params}))
handler.add_constraint(DepthConstraint(min_depth=5, max_depth=20))

# Create adaptive scheduler
scheduler = AdaptiveOperatorScheduler(
    initial_crossover=0.8,
    initial_mutation=0.2
)

# Run optimization
evaluator = HeuristicEvaluator()
optimizer = GeneticAlgorithm(space, config={{
    "population_size": {population_size},
    "num_generations": {num_generations},
}})

print("Running advanced NAS with adaptive operators...")
best = optimizer.optimize(evaluator)

# Visualize if parents available
if best.parent_ids and len(best.parent_ids) == 2:
    try:
        quick_crossover_viz(
            optimizer.population.get(best.parent_ids[0]).graph,
            optimizer.population.get(best.parent_ids[1]).graph,
            "best_parents_crossover.png"
        )
        print("\\n✓ Saved crossover visualization")
    except Exception as e:
        print(f"\\nVisualization skipped: {{e}}")

# Export
exporter = ArchitectureExporter()
code = exporter.to_pytorch(best.graph, "{name}_model")
with open("{name}_model.py", 'w') as f:
    f.write(code)

print(f"\\n✓ Best architecture exported!")
print(f"  Fitness: {{best.fitness:.4f}}")
print(f"  Parameters: {{best.graph.estimate_parameters():,}}")
""",
}


@click.command()
@click.option(
    "--template",
    "-t",
    type=click.Choice(["cnn_classification", "simple_nas", "advanced_nas"]),
    default="cnn_classification",
    help="Template type",
)
@click.option("--name", "-n", default="my_nas", help="Project name")
@click.option("--output", "-o", default=None, help="Output file path")
@click.option("--num-classes", default=10, help="Number of output classes")
@click.option("--max-params", default=1000000, help="Maximum parameters constraint")
@click.option("--population-size", default=20, help="Population size")
@click.option("--num-generations", default=50, help="Number of generations")
@click.option("--interactive", "-i", is_flag=True, help="Interactive mode")
def quickstart(
    template: str,
    name: str,
    output: Optional[str],
    num_classes: int,
    max_params: int,
    population_size: int,
    num_generations: int,
    interactive: bool,
):
    """
    Generate a quick-start NAS project from template.

    Examples:
        morphml quickstart
        morphml quickstart -t simple_nas -n my_project
        morphml quickstart -i  # Interactive mode
    """
    # Interactive mode
    if interactive:
        click.echo("🧬 MorphML Quick Start - Interactive Mode\n")

        template = click.prompt(
            "Select template",
            type=click.Choice(["cnn_classification", "simple_nas", "advanced_nas"]),
            default="cnn_classification",
        )
        name = click.prompt("Project name", default="my_nas")
        num_classes = click.prompt("Number of classes", default=10, type=int)

        if template in ["cnn_classification", "advanced_nas"]:
            max_params = click.prompt("Max parameters", default=1000000, type=int)
            population_size = click.prompt("Population size", default=20, type=int)
            num_generations = click.prompt("Number of generations", default=50, type=int)

    # Generate code from template
    template_code = TEMPLATES[template]
    code = template_code.format(
        name=name,
        num_classes=num_classes,
        max_params=max_params,
        population_size=population_size,
        num_generations=num_generations,
    )

    # Determine output file
    if output is None:
        output = f"{name}.py"

    output_path = Path(output)

    # Check if file exists
    if output_path.exists():
        if not click.confirm(f"File {output} already exists. Overwrite?"):
            click.echo("Aborted.")
            return

    # Write file
    output_path.write_text(code)

    # Success message
    click.echo(f"\n✓ Created {output}")
    click.echo(f"\nTemplate: {template}")
    click.echo(f"Project: {name}")
    click.echo(f"Classes: {num_classes}")

    if template in ["cnn_classification", "advanced_nas"]:
        click.echo(f"Max params: {max_params:,}")
        click.echo(f"Population: {population_size}")
        click.echo(f"Generations: {num_generations}")

    click.echo(f"\nNext steps:")
    click.echo(f"  1. Review and customize {output}")
    click.echo(f"  2. Run: python {output}")
    click.echo(f"  3. Check exported model file")

    # Show template description
    descriptions = {
        "cnn_classification": "Full CNN classification with constraints and export",
        "simple_nas": "Minimal NAS example for quick testing",
        "advanced_nas": "Advanced NAS with adaptive operators and visualization",
    }
    click.echo(f"\nTemplate: {descriptions[template]}")


if __name__ == "__main__":
    quickstart()
