#!/bin/bash
# Compile Protocol Buffer definitions for distributed communication
# Author: Eshan Roy <eshanized@proton.me>
# Organization: TONMOY INFRASTRUCTURE & VISION

set -e

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
PROJECT_ROOT="$(dirname "$SCRIPT_DIR")"

echo "========================================="
echo "  MorphML Protocol Buffer Compilation"
echo "========================================="
echo ""

# Check for grpcio-tools
if ! python3 -c "import grpc_tools.protoc" 2>/dev/null; then
    echo "ERROR: grpcio-tools not installed"
    echo "Install with: pip install grpcio-tools"
    exit 1
fi

echo "✓ grpcio-tools found"
echo ""

# Directories
PROTO_DIR="$PROJECT_ROOT/morphml/distributed/proto"
OUTPUT_DIR="$PROTO_DIR"

echo "Compiling .proto files..."
echo "  Source:  $PROTO_DIR"
echo "  Output:  $OUTPUT_DIR"
echo ""

# Compile worker.proto
echo "Compiling worker.proto..."
python3 -m grpc_tools.protoc \
    -I"$PROTO_DIR" \
    --python_out="$OUTPUT_DIR" \
    --grpc_python_out="$OUTPUT_DIR" \
    --pyi_out="$OUTPUT_DIR" \
    "$PROTO_DIR/worker.proto"

if [ $? -eq 0 ]; then
    echo "✓ worker.proto compiled successfully"
else
    echo "✗ Failed to compile worker.proto"
    exit 1
fi

echo ""

# Fix imports in generated files (common protobuf issue)
echo "Fixing imports in generated files..."

# Fix worker_pb2_grpc.py imports
if [ -f "$OUTPUT_DIR/worker_pb2_grpc.py" ]; then
    # Change "import worker_pb2" to "from . import worker_pb2"
    if [[ "$OSTYPE" == "darwin"* ]]; then
        # macOS sed
        sed -i '' 's/^import worker_pb2/from . import worker_pb2/' "$OUTPUT_DIR/worker_pb2_grpc.py"
    else
        # Linux sed
        sed -i 's/^import worker_pb2/from . import worker_pb2/' "$OUTPUT_DIR/worker_pb2_grpc.py"
    fi
    echo "✓ Fixed imports in worker_pb2_grpc.py"
fi

echo ""

# Create __init__.py if it doesn't exist
INIT_FILE="$OUTPUT_DIR/__init__.py"
if [ ! -f "$INIT_FILE" ]; then
    cat > "$INIT_FILE" << 'EOF'
"""Generated Protocol Buffer stubs for distributed communication.

Auto-generated by scripts/compile_protos.sh
Do not edit manually.
"""

from morphml.distributed.proto.worker_pb2 import *
from morphml.distributed.proto.worker_pb2_grpc import *

__all__ = [
    'worker_pb2',
    'worker_pb2_grpc',
]
EOF
    echo "✓ Created __init__.py"
fi

echo ""
echo "========================================="
echo "  Compilation Complete!"
echo "========================================="
echo ""
echo "Generated files:"
ls -lh "$OUTPUT_DIR"/*.py 2>/dev/null | awk '{print "  " $9 "  (" $5 ")"}'
echo ""
echo "You can now import with:"
echo "  from morphml.distributed.proto import worker_pb2, worker_pb2_grpc"
echo ""
