#!/usr/bin/env python3
"""Compile Protocol Buffer definitions for distributed communication.

Author: Eshan Roy <eshanized@proton.me>
Organization: TONMOY INFRASTRUCTURE & VISION
"""

import os
import sys
from pathlib import Path

# Add project root to path
PROJECT_ROOT = Path(__file__).parent.parent
sys.path.insert(0, str(PROJECT_ROOT))


def main() -> int:
    """Compile protobuf files."""
    print("=" * 60)
    print("  MorphML Protocol Buffer Compilation")
    print("=" * 60)
    print()

    # Check for grpcio-tools
    try:
        from grpc_tools import protoc
    except ImportError:
        print("ERROR: grpcio-tools not installed")
        print("Install with one of:")
        print("  poetry install --extras distributed")
        print("  pip install grpcio-tools")
        return 1

    print("✓ grpcio-tools found")
    print()

    # Directories
    proto_dir = PROJECT_ROOT / "morphml" / "distributed" / "proto"
    output_dir = proto_dir

    if not proto_dir.exists():
        print(f"ERROR: Proto directory not found: {proto_dir}")
        return 1

    proto_file = proto_dir / "worker.proto"
    if not proto_file.exists():
        print(f"ERROR: Proto file not found: {proto_file}")
        return 1

    print("Compiling .proto files...")
    print(f"  Source:  {proto_dir}")
    print(f"  Output:  {output_dir}")
    print()

    # Compile worker.proto
    print("Compiling worker.proto...")

    # Build protoc arguments
    args = [
        "grpc_tools.protoc",  # Program name
        f"-I{proto_dir}",  # Include path
        f"--python_out={output_dir}",  # Python output
        f"--grpc_python_out={output_dir}",  # gRPC output
        f"--pyi_out={output_dir}",  # Type stubs
        str(proto_file),  # Proto file
    ]

    result = protoc.main(args)

    if result != 0:
        print("✗ Failed to compile worker.proto")
        return 1

    print("✓ worker.proto compiled successfully")
    print()

    # Fix imports in generated files
    print("Fixing imports in generated files...")

    grpc_file = output_dir / "worker_pb2_grpc.py"
    if grpc_file.exists():
        content = grpc_file.read_text()

        # Fix import: "import worker_pb2" -> "from . import worker_pb2"
        if "import worker_pb2" in content:
            content = content.replace(
                "import worker_pb2 as worker__pb2",
                "from . import worker_pb2 as worker__pb2",
            )
            grpc_file.write_text(content)
            print("✓ Fixed imports in worker_pb2_grpc.py")

    # Create/update __init__.py
    init_file = output_dir / "__init__.py"
    init_content = '''"""Generated Protocol Buffer stubs for distributed communication.

Auto-generated by scripts/compile_protos.py
Do not edit manually.
"""

try:
    from morphml.distributed.proto.worker_pb2 import *
    from morphml.distributed.proto.worker_pb2_grpc import *

    __all__ = [
        "worker_pb2",
        "worker_pb2_grpc",
    ]
except ImportError:
    # Protobuf files not generated yet
    pass
'''
    init_file.write_text(init_content)
    print("✓ Created/updated __init__.py")
    print()

    # List generated files
    print("=" * 60)
    print("  Compilation Complete!")
    print("=" * 60)
    print()
    print("Generated files:")

    for py_file in output_dir.glob("*.py"):
        if py_file.name != "__init__.py":
            size = py_file.stat().st_size
            print(f"  {py_file.name}  ({size:,} bytes)")

    print()
    print("You can now import with:")
    print("  from morphml.distributed.proto import worker_pb2, worker_pb2_grpc")
    print()

    return 0


if __name__ == "__main__":
    sys.exit(main())
